spring.datasource.url=jdbc:postgresql://localhost:5432/first_demo
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=DhS9ccDQ1bql6H6eIl8wXQGgjxXSbM70iGG3Uz+ptr4=
jwt.expiration=3600000